framework:
    messenger:
        transports:
            kafka_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext' # plaintext, ssl, sasl_plaintext, sasl_ssl
                    group.id: 'my-group-id' # consumer group id
                    auto.offset.reset: 'earliest' # 'earliest': start from the beginning
                    enable.partition.eof: true # Emit EOF event when reaching the end of a partition
                    #allow.auto.create.topics: true # Allow automatic topic creation on the broker
                    #ssl.certificate.location: ''
                    message.send.max.retries: 5
                    producer_topic: 'producer_topic'
                    consumer_topics:
                        - 'producer_topic'

        routing:
            'App\Messenger\Message\OrderPaidMessage': kafka_transport

        serializer:
            default_serializer: messenger.transport.symfony_serializer

when@test:
    framework:
        messenger:
            transports:
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                kafka_transport: 'in-memory://'
