version: '3.8'

services:
  php:
    container_name: sf-messenger-kafka-php
    depends_on:
      - kafka
    build:
      context: .
      target: local
    volumes:
      - '.:/var/www/symfony'

  zookeeper:
    container_name: sf-messenger-kafka-zookeeper
    build:
      context: .docker/zookeeper
    ports:
      - '2181:2181'

  # todo: replication
  kafka:
    container_name: sf-messenger-kafka-server
    build:
      context: .docker/kafka
    command:
      - --override
      - broker.id=1
      - --override
      - zookeeper.connect=zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  redis_data:
    driver: local
